name: Download Gifts Assets

on:
  workflow_dispatch:
  push:
    paths:
      - "data/gifts.json"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios fs-extra

      - name: Run download script
        run: node .github/scripts/download.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images json
          git commit -m "Update gifts assets" || echo "No changes to commit"
          git push
